title: 'biscoewilson | architects'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7851064
  brandStrength: 0.9021277
  lightness: 0.5808511
  brandColors:
    - '#030302'
    - '#A1A5BD'
    - '#5C534B'
    - '#D83903'
    - '#B49B02'
  rhythmicContrast: 0.612766
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'BiscoeWilson | Architects'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5319149
layout_spectrum: 0.7787234
